### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by gommzystudio** [TheLonelySheep/BetterZoom#12]
When I open the game with the mod. The games crashes 😕
It’s very sad, because I love the mod.

**Comment by NotLe0n** [comment]
Please attach the client.log file.

You should be able to find it here:
Windows: `\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader-Logs`
Linux: `~/.local/share/Terraria/ModLoader/Logs/` or `$XDG_DATA_HOME/Terraria/ModLoader/Logs/`
Mac: `~/Library/Application support/Terraria/ModLoader/Logs/`

**Comment by gommzystudio** [comment]
I'm using android

**Comment by NotLe0n** [comment]
You are playing tModLoader on your android phone?

**Comment by gommzystudio** [comment]
No I’m using android modloader

**Comment by NotLe0n** [comment]
This mod is only supported on tModLoader, which doesn't exist on android. You can not expect a mod to work on any third-party modloader. I will not be "fixing" this as it's not a problem on a platform I support.

**Comment by gommzystudio** [comment]
Now my Minecraft client is crashing too 👎

**Comment by gommzystudio** [comment]
I created a video of the game crash https://youtu.be/dQw4w9WgXcQ
